// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Edu struct {
	ID             int     `json:"id"`
	School         *string `json:"school"`
	Major          *string `json:"major"`
	Gpa            *string `json:"gpa"`
	GraduationDate *string `json:"graduationDate"`
	Description    *string `json:"description"`
}

type Experience struct {
	ID          int     `json:"id"`
	Company     *string `json:"company"`
	JobTitle    *string `json:"jobTitle"`
	City        *string `json:"city"`
	State       *string `json:"state"`
	Zip         *string `json:"zip"`
	Description *string `json:"description"`
	StartDate   *string `json:"startDate"`
	EndDate     *string `json:"endDate"`
}

type Message struct {
	ID      int     `json:"id"`
	Email   *string `json:"email"`
	Phone   *string `json:"phone"`
	Subject *string `json:"subject"`
	Message *string `json:"message"`
}

type Project struct {
	ID   int     `json:"id"`
	Name *string `json:"name"`
	Icon *string `json:"icon"`
	Link *string `json:"link"`
}

type EduInput struct {
	ID             *int    `json:"id"`
	School         *string `json:"school"`
	Major          *string `json:"major"`
	Gpa            *string `json:"gpa"`
	GraduationDate *string `json:"graduationDate"`
	Description    *string `json:"description"`
}

type ExperienceInput struct {
	ID          *int    `json:"id"`
	Company     *string `json:"company"`
	JobTitle    *string `json:"jobTitle"`
	City        *string `json:"city"`
	State       *string `json:"state"`
	Zip         *string `json:"zip"`
	Description *string `json:"description"`
	StartDate   *string `json:"startDate"`
	EndDate     *string `json:"endDate"`
}

type MessageInput struct {
	Email   *string `json:"email"`
	Phone   *string `json:"phone"`
	Subject *string `json:"subject"`
	Message *string `json:"message"`
}

type ProjectInput struct {
	ID   *int    `json:"id"`
	Name *string `json:"name"`
	Icon *string `json:"icon"`
	Link *string `json:"link"`
}

type UserInput struct {
	ID        *int    `json:"id"`
	Username  *string `json:"username"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Address   *string `json:"address"`
	City      *string `json:"city"`
	Zip       *string `json:"zip"`
	Email     *string `json:"email"`
	Phone     *string `json:"phone"`
	Photo     *string `json:"photo"`
}
